### ISSUE TITLE
url_shortner

### ISSUE THREAD

**Issue by rinzes** [andreimarcu/aamnews#26]
Need some guidance on how to config aamnews to use tinyurl shortner

**Comment by andreimarcu** [comment]
If you don't want to do it yourself you can use something like https://github.com/daxeel/TinyURL-Python and plug it directly in the `shorten_url` method

**Comment by rinzes** [comment]
ok, I've gotten tinyurl and added import tinyurl in the config file. now can you help me with the plugin to shorten_url

**Comment by andreimarcu** [comment]
Probably something like this:

``` python
def shorten_url(url):
    return tinyurl.shorten(url, "")

```

**Comment by rinzes** [comment]
I decided to go with this site because it supports python3 https://github.com/Cheeselab/TinyURL. However, I get Twitter error: create_one() takes 1 positional argument but 2 were given for MarketCurrents

So how does 1 handle 1 argument for RSS and 2 for Twitter

**Comment by rinzes** [comment]
Anyway I've ran into a glitch... I have it config with return TinyURL.TinyURL.create_one(url, "")and get the following output:

GBN: Elon Musk: Launch pad explosion is 'most difficult and complex' failure in SpaceX's 14 years - Los Angeles `Times[<generator` object create at0xb5eddaf4> ]

Any ideas?

**Comment by AraHaan** [comment]
The issue is it should call `create_one` with just the `url` as it only assepts are arangement with the actual url string.

So, proper usage should be:

```
import TinyURL

def shorten_url(url):
    # This is because the url must be a string and as such must only be coded like this.
    TinyURL.TinyURL.create_one(url) 
```

Currently `create_one` checks if it starts with `https://`, or `http://`, or `ftp://` (the most common) **and** checks to see if it is empty or not. If it is empty it raises a `TinyURL.errors.URLError` error and if it does not start with any of the following: `http://`, `https://`, or `ftp://` to raise a `TinyURL.errorsInvalidURL` error. This should be helpful. Now this is only if it is only 1 url if it is a list then `create` has to be used.

**Comment by AraHaan** [comment]
Now that I see some parts maybe I could try to support creating aliases or something where you can influence the generated url.

**Comment by AraHaan** [comment]
Ok, I think I did it but it needs some testing uploading a non final one on pypi. Hopefully it will work. If so I will finalize it.
https://pypi.python.org/pypi/TinyURL3/0.1.6
